PCHR-1711: Fix Failing Test on HRSampleData
CRM_HRSampleData_CSVProcessor_AbsenceTypeTest::testProcesor() test was failing
with an error, due to an exception being thrown in createActivityType() method
of CRM_HRAbsence_BAO_HRAbsenceType class:

  CiviCRM_API3_Exception: Undefined index: debit_activity_type_id

Fixed removing offending assignations of unset array key.